import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/providers/ThemeProviders";
import { Toaster } from "react-hot-toast";
import ModelsProvider from "@/components/ui/providers/ModelsProvider";
import "react-quill/dist/quill.snow.css";
import "quill/dist/quill.core.css";
import Quill from "quill/core";
import Toolbar from "quill/modules/toolbar";
import Snow from "quill/themes/snow";

import Bold from "quill/formats/bold";
import Italic from "quill/formats/italic";
import Header from "quill/formats/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Docs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} h-full`}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <ModelsProvider />
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
