import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/providers/ThemeProviders";
import { Toaster } from "react-hot-toast";
import ModelsProvider from "@/components/ui/providers/ModelsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Toaster />
          <ModelsProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
